#!/usr/bin/env python3
"""BUILDER-LIGHT r25 - the sealed crop set. Generated by script, left unscored.

It REUSES tools/r24_blindset.py, which reuses tools/r22_blindset.py. Nothing
about tile size, MIN_PROD, the per-pose cap, the contributing-pose guard, the
photo pool or the symmetric one-encoder q88 4:2:0 normalisation is restated
here - all of it is imported. The only thing this file adds is the two arm
names and their masks, because MASK_OF is a registry and a round that copies
the whole script to change one dict entry is how a second owner starts.

THE MASK QUESTION, ANSWERED RATHER THAN ASSUMED. r24 had to give each arm its
own mask because it moved every facing's orientation, so the package silhouette
itself differed. This round moves ONE UNIFORM and no geometry, so the two arms'
silhouettes should be identical. That is not assumed: both masks are captured
and compared, and the pure-green sets agree pixel for pixel at all six poses -
348260 / 625892 / 282790 / 191823 / 234464 / 221181, diff 0. Each arm is still
gated on its own mask, because a registry entry that is correct by coincidence
is the thing this repo keeps writing entries about.

LEAK 5 (content matching) is handled the way r22_blindset says to handle it:
photo_tiles() defaults to the SHELF_FACE subject list, so the photograph side is
packed shelf aisles rather than produce, checkout lanes or vistas, and the
report names the files a set drew. r24's r24on arm drew vistas and floral and
"did not test what it claims".

The builder has read light.js and store.js and does not open the key.

    python3 tools/r25_blindset.py r25on  shots/blind_<name> [seed]
    python3 tools/r25_blindset.py r25off shots/blind_<name> [seed]
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import r24_blindset as R24                                  # noqa: E402

R24.MASK_OF['r25on'] = 'r25mask_on'
R24.MASK_OF['r25off'] = 'r25mask_off'

if __name__ == '__main__':
    R24.main()
