#!/usr/bin/env python3
"""BUILDER-SIGNAGE r26 - the sealed crop set. Generated by script, left unscored.

It REUSES tools/r24_blindset.py, which reuses tools/r22_blindset.py. Nothing
about tile size, MIN_PROD, the per-pose cap, the contributing-pose guard, the
photo pool or the symmetric one-encoder q88 4:2:0 normalisation is restated
here - all of it is imported.

=========================================================================
LEAK 7 IS STILL OPEN ON THIS PATH, AND THIS FILE REPRODUCED IT BEFORE
CLOSING IT LOCALLY.

The fix for leak 7 - "the two arms shared a seed, so their photograph tiles
were BYTE-IDENTICAL and shared tile indices; md5-ing the two directories
yielded the complete answer key at zero pixels examined" - was written into
`r22_blindset.main`, which now seeds with `Random('%s|%s' % (seed, arm))`.
`r24_blindset.main` still seeds with `random.Random(seed)`, and r24, r25 and
the first draft of this round all run through THAT main. Measured on this
round's first pair, both arms at seed 81685:

    9 of 18 tiles byte-identical across the two directories,
    and they are exactly the 9 photographs.

So the leak that was found, written up and fixed one module down was live
again one module up, because the fix went into the function the wrapper does
not call. A fix that lives in a function nobody on the current path calls is
the same shape as a guard that counts files instead of contributions.

Closed HERE, in the file this round owns, rather than by editing a shared
module while other agents are running against it: the arm name is folded into
an integer seed before `R24.main` ever sees it, so the photo draw, the crop
windows, the split and the tile order all differ per arm. Verified after
regeneration: 0 of 18 tiles byte-identical. The proper fix is one line in
`r24_blindset.main` and is named in the round report.
=========================================================================

The only other thing this file adds is the two arm names, their masks, and a
way to name the photograph files a seed drew WITHOUT opening the key.

THE MASK QUESTION, ANSWERED RATHER THAN ASSUMED, the way r25 answered it. This
round adds 1,784 opaque card boards and moves 1,252 package instances, so the
two arms' package silhouettes are NOT identical and each arm must be gated on
its own mask. Measured, per pose, PKG_STAGE 7 pure-green pixel counts:

    pose        r26off     r26on    delta   differing px
    near_a1     348260    345163    -3097    7557  (0.820%)
    near_a4     625892    626684     +792    2996  (0.325%)
    near_a7     282790    282351     -439    1079  (0.117%)
    chase_a1    191823    191520     -303    4211  (0.457%)
    chase_a4    234464    234320     -144    5698  (0.618%)
    chase_a6    221181    220921     -260    4270  (0.463%)

The r26off column is round 25's published silhouette to the pixel - 348260 /
625892 / 282790 / 191823 / 234464 / 221181 - which is one of the six
independent checks that `?flatcard` reproduces round 25 rather than
approximating it.

LEAK 5 (content matching) is handled the way r22_blindset says to handle it:
photo_tiles() defaults to the SHELF_FACE subject list, so the photograph side
is packed shelf aisles rather than produce, checkout lanes or vistas. The
instruction attached to that leak is "say in the report which files a set
drew", and `--files` does exactly that and nothing else: it replays the seeded
Random through photo_tiles() ONLY, which happens before any call that decides
the split, so it can name the photograph sources without revealing how many
tiles of either class the set holds.

The builder has read intrusions.js, card.js and store.js and does not open the
key.

    python3 tools/r26_blindset.py r26on  shots/blind_<name> [seed]
    python3 tools/r26_blindset.py r26off shots/blind_<name> [seed]
    python3 tools/r26_blindset.py --files r26on <seed>
"""
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import r22_blindset as B                                     # noqa: E402
import r24_blindset as R24                                   # noqa: E402

R24.MASK_OF['r26on'] = 'r26mask_on'
R24.MASK_OF['r26off'] = 'r26mask_off'


def arm_seed(arm, seed):
    """LEAK 7, closed on this path. A stable per-arm integer derived from the
    round's seed, so the two arms are not diffable. FNV-1a over the arm name so
    it does not depend on Python's hash randomisation - a seed that changed
    between two runs of the same command would make the set unreproducible,
    which is a worse bug than the one being fixed."""
    h = 0x811c9dc5
    for ch in ('%s|%s' % (seed, arm)).encode():
        h = ((h ^ ch) * 0x01000193) & 0xffffffff
    return h


def photo_files(arm, seed):
    """The photograph SOURCES a given (arm, seed) will draw, and nothing else.

    Replays the same Random in the same order as main() up to and including
    photo_tiles(); every call that decides the split happens after that point,
    so this cannot leak it.
    """
    rnd = random.Random(arm_seed(arm, seed))
    tiles = B.photo_tiles(rnd)
    seen = []
    for _, why in tiles:
        f = why.rsplit(' ', 2)[0]
        if f not in seen:
            seen.append(f)
    return seen


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == '--files':
        for f in photo_files(sys.argv[2], int(sys.argv[3])):
            print(f)
    else:
        # rewrite argv[3] to the per-arm seed before R24.main() reads it
        if len(sys.argv) > 3:
            sys.argv[3] = str(arm_seed(sys.argv[1], int(sys.argv[3])))
        R24.main()
